FROM python:3.8

RUN pip install Flask

#RUN mkdir -p /app

WORKDIR /app

COPY run.py .

ENV APP_DIRS="/Ruuter /Resql /DataMapper /Liquibase /OpenSearch /bot"
RUN mkdir -p $APP_DIRS

COPY Ruuter/private/v2/analytics /Ruuter/analytics
COPY Resql/analytics /Resql/analytics
COPY DataMapper/v1/analytics /DataMapper/analytics
COPY Liquibase/analytics /Liquibase/analytics

LABEL org.opencontainers.image.description Docker PRE-ALPHA image for Buerokratt-DSL

CMD ["python", "run.py"]
