-- liquibase formatted sql
-- changeset gertdrui:1674046339
CREATE TABLE public."user_overview_metric_preference" (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id_code VARCHAR(50) NOT NULL,
    metric overview_metric NOT NULL,
    ordinality int NOT NULL DEFAULT 0,
    active boolean NOT NULL DEFAULT false,
    CONSTRAINT user_overview_metric_preference_pkey PRIMARY KEY (id)
);
