-- liquibase formatted sql
-- changeset gertdrui:1676218580
CREATE TABLE public."scheduled_reports" (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(150) NOT NULL,
    dataset_id VARCHAR(150) NOT NULL,
    job_id VARCHAR(150) NOT NULL,
    period VARCHAR(50) NOT NULL,
    metrics TEXT[] NOT NULL,
    created timestamptz NOT NULL DEFAULT NOW(),
    updated timestamptz NULL DEFAULT NOW(),
    CONSTRAINT scheduled_reports_pkey PRIMARY KEY (id)
);
