get_services_list:
  call: http.post
  args:
    url: "[#SERVICE_RESQL]:[#SERVICE_RESQL_PORT]/get-services-list"
  result: results

return_ok:
  status: 200
  return: ${results.response.body}
  next: end
