name: Buerokratt DSL

on:
  push:
    branches:
      - varmo-gha-testing # Adjust the branch name if needed

jobs:
  setup_directories:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check and Create Folder Structure and copy DSLs
        run: |
          FOLDER_PATH=Ruuter/private/v2/
          if [ ! -d "$FOLDER_PATH" ]; then
            echo "Folder structure does not exist, creating..."
            mkdir -p "$FOLDER_PATH"
            touch "$FOLDER_PATH/README.md"
          else
            echo "Folder structure already exists."
          fi

      - name: Create Subfolders
        run: |
          SUBFOLDERS=("analytics" "backoffice" "services" "training")
          for folder in "${SUBFOLDERS[@]}"; do
            FOLDER_PATH="$FOLDER_PATH$folder"
            if [ ! -d "$FOLDER_PATH" ]; then
              echo "Creating $folder folder..."
              mkdir -p "$FOLDER_PATH"
              touch "$FOLDER_PATH/README.md"
            else
              echo "$folder folder already exists."
            fi
          done

          SOURCE_REPO_CHATBOT=buerokratt/Buerokratt-Chatbot
          SOURCE_FOLDER_CHATBOT=DSL.Ruuter.private/DSL
          git clone "https://github.com/$SOURCE_REPO_CHATBOT.git" source-repo-chatbot
          cp -R "source-repo-chatbot/$SOURCE_FOLDER_CHATBOT" "$FOLDER_PATH/backoffice"

          SOURCE_REPO_ANALYTICS=buerokratt/Analytics-Module
          SOURCE_FOLDER_ANALYTICS=DSL/Ruuter
          git clone "https://github.com/$SOURCE_REPO_ANALYTICS.git" source-repo-analytics
          cp -R "source-repo-analytics/$SOURCE_FOLDER_ANALYTICS" "$FOLDER_PATH/analytics"

          SOURCE_REPO_SERVICE=buerokratt/Service-Module
          SOURCE_FOLDER_SERVICE=DSL/Ruuter
          git clone "https://github.com/$SOURCE_REPO_SERVICE.git" source-repo-service
          cp -R "source-repo-service/$SOURCE_FOLDER_SERVICE" "$FOLDER_PATH/services"

       

     

      - name: Commit and Push Folder Structure with Copied Contents
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add Ruuter
          git diff-index --quiet HEAD || git commit -m "Copy contents and update folder structure using GitHub Actions"
          git push
