name: Buerokratt DSL

on:
  push:
    branches:
      - varmo-gha-testing # Adjust the branch name if needed

jobs:
  setup_directories:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if directories exist
        run: |
          if [ ! -d "RUUTER/private/v2/backoffice/" ]; then
            mkdir -p RUUTER/private/v2/backoffice/
          fi
          if [ ! -d "RUUTER/private/analytics/" ]; then
            mkdir -p RUUTER/private/analytics/
          fi
          if [ ! -d "RUUTER/private/training/" ]; then
            mkdir -p RUUTER/private/training/
          fi
          if [ ! -d "RUUTER/private/services/" ]; then
            mkdir -p RUUTER/private/services/
          fi
        working-directory: ${{ github.workspace }}

  copy_backoffice:
    runs-on: ubuntu-22.04
    needs: setup_directories

    steps:
      - name: Checkout DSL Repository
        uses: actions/checkout@v2
        with:
          repository: varmoh/Buerokratt-Chatbot
          path: DSL

      - name: Copy GET files to backoffice
        run: |
          cp -R DSL/DSL.Ruuter.private/DSL/GET/. RUUTER/private/v2/backoffice/
        working-directory: ${{ github.workspace }}

      - name: Copy POST files to backoffice
        run: |
          cp -R DSL/DSL.Ruuter.private/DSL/POST/. RUUTER/private/v2/backoffice/
        working-directory: ${{ github.workspace }}

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Copy backoffice files from CHATBOT repository"
          git push origin main # Or the appropriate branch
