name: Buerokratt DSL

on:
  push:
    branches:
      - varmo-gha-testing # Adjust the branch name if needed

jobs:

  setup_directories:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check and Create Folder Structure
        run: |
          FOLDER_PATH=Ruuter/private/v2/backoffice

          if [ ! -d "$FOLDER_PATH" ]; then
            echo "Folder structure does not exist, creating..."
            mkdir -p "$FOLDER_PATH"
          else
            echo "Folder structure already exists."
          fi

      - name: Commit and Push Folder Structure Creation
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add Ruuter
          git diff-index --quiet HEAD || git commit -m "Create or update folder structure using GitHub Actions"
          git push
