name: Buerokratt DSL

on:
  push:
    branches:
      - varmo-gha-testing # Adjust the branch name if needed
    paths:
      - 'DSL.md' #this trigger is for testing purposes only

jobs:
  setup_directories:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check and Create Folder Structure and copy DSLs
        run: |
          FOLDER_PATH=Ruuter/private/v2/
          if [ ! -d "$FOLDER_PATH" ]; then
            echo "Folder structure does not exist, creating..."
            mkdir -p "$FOLDER_PATH"
            touch "$FOLDER_PATH/README.md"
          else
            echo "Folder structure already exists."
          fi

          SUBFOLDERS=("analytics" "backoffice" "services" "training")
          for folder in "${SUBFOLDERS[@]}"; do
            SUBFOLDER_PATH="$FOLDER_PATH$folder"
            if [ ! -d "$SUBFOLDER_PATH" ]; then
              echo "Creating $folder folder..."
              mkdir -p "$SUBFOLDER_PATH"
              touch "$SUBFOLDER_PATH/README.md"
            else
              echo "$folder folder already exists."
            fi
          done

          SOURCE_REPO_CHATBOT=buerokratt/Buerokratt-Chatbot
          SOURCE_FOLDER_CHATBOT=DSL.Ruuter.private/DSL
          git clone --depth=1   "https://github.com/$SOURCE_REPO_CHATBOT.git" source-repo-chatbot
          cp -R "source-repo-chatbot/$SOURCE_FOLDER_CHATBOT/." "$FOLDER_PATH/backoffice"

          SOURCE_REPO_ANALYTICS=buerokratt/Analytics-Module
          SOURCE_FOLDER_ANALYTICS=DSL/Ruuter
          git clone --depth=1 "https://github.com/$SOURCE_REPO_ANALYTICS.git" source-repo-analytics
          cp -R "source-repo-analytics/$SOURCE_FOLDER_ANALYTICS/." "$FOLDER_PATH/analytics"

          SOURCE_REPO_SERVICE=buerokratt/Service-Module
          SOURCE_FOLDER_SERVICE=DSL/Ruuter
          git clone --depth=1 "https://github.com/$SOURCE_REPO_SERVICE.git" source-repo-service
          cp -R "source-repo-service/$SOURCE_FOLDER_SERVICE/." "$FOLDER_PATH/services"

          SOURCE_REPO_TRAINING=buerokratt/Training-Module
          SOURCE_FOLDER_TRAINING=DSL/Ruuter.private
          git clone --depth=1  "https://github.com/$SOURCE_REPO_TRAINING.git" source-repo-training
          cp -R "source-repo-training/$SOURCE_FOLDER_TRAINING/." "$FOLDER_PATH/training"

          # Print copied files to changelog.md
          
           echo "Copied Files:" >> changelog.md
           find "$FOLDER_PATH" -type f >> changelog.md

      - name: Create Empty README.md
        run: touch Ruuter/private/v2/backoffice/README.md

      - name: Commit and Push Folder Structure with Copied Contents
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add Ruuter
          git diff-index --quiet HEAD || git commit -m "Copy contents and update folder structure using GitHub Actions"
          git push

      - name: Create Changelog
        run: |
          sed -i 's/$/\n/' changelog.md  # Add a line break at the end of each line
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add chnagelog.md
          git diff-index --quiet HEAD || git commit -m "Add changelog with copied files"
          git push

      - name: Clean Up Cloned Repositories
        run: |
          rm -rf source-repo-chatbot
          rm -rf source-repo-analytics
          rm -rf source-repo-service
          rm -rf source-repo-training
