name: Buerokratt DSL

on:
  push:
    branches:
      - varmo-gha-testing # Adjust the branch name if needed

jobs:

  setup_directories:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if directories exist
        run: |
            if [ ! -d "RUUTER/private/v2/backoffice/" ]; then
            mkdir -p RUUTER/private/v2/backoffice/
            fi
        working-directory: ${{ github.workspace }}

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Copy backoffice files from CHATBOT repository"
          git push origin main # Or the appropriate branch
